### ISSUE TITLE
Paragraphs from WYSIWYG field

### ISSUE THREAD

**Issue by Grawl** [kucrut/kc-settings#10]
When I `echo` WYSIWYG field I don't have paragraphs in HTML – everything except `<p>`'s, but I want them.

Dashboard → Settings → KS Settings field settings:
![2013-11-14 14 44 27](https://f.cloud.github.com/assets/846774/1538258/218fc2bc-4cdf-11e3-85f7-1a868cbf2f5d.png)

Field content:
![2013-11-14 14 42 12](https://f.cloud.github.com/assets/846774/1538262/4fb86860-4cdf-11e3-975d-bbcc484ffa62.png)

Command to output it:

``` php
<aside class="description"><?
    echo kc_get_option( 'theme', 'view', 'description')
?></aside>
```

Output HTML:

``` html
<aside class="description">город Владивосток,
Прапорщика Комарова, 45

<span style="color: #888888;">+7 (423)</span> 279-57-10</aside>
```

Expected output:

``` html
<aside class="description">
<p>город Владивосток,<br>
Прапорщика Комарова, 45</p>

<p><span style="color: #888888;">+7 (423)</span> 279-57-10</p></aside>
```

**Comment by Grawl** [comment]
If I set alignment to left or right, paragraphs exists in output. But it's a workaround, there's need clean solution.

**Comment by kucrut** [comment]
You should use `wpautop()`:

``` php
echo wpautop( kc_get_option( 'theme', 'view', 'description') );
```

**Comment by Grawl** [comment]
Works as expected. Thank you.
