### ISSUE TITLE
wysiwyg in textareas

### ISSUE THREAD

**Issue by anabelle** [kucrut/kc-settings#2]
This is not an issue but more a question.

Is it possible to enable TinyMCE in textarea fields?

**Comment by kucrut** [comment]
I plan to add this feature, but still need to figure out the best way, 
because wp_editor() doesn't behave nicely inside metabox.
This is also the reason why I didn't use metaboxes for KCML translation.

http://codex.wordpress.org/Function_Reference/wp_editor#Notes

**Comment by kucrut** [comment]
Forgot to close this. The feature was added :)
