### ISSUE TITLE
Repeatable fields

### ISSUE THREAD

**Issue by anabelle** [kucrut/kc-settings#3]
Hi, 

I don't know if you know the plugin simple-fields, kd-settings is better in many ways, but one lacking feature in kc-settings is the ability to add repeatable fields.

That means, one type of field that can be different number of times in a meta box. Is this possible?

**Comment by kucrut** [comment]
This is already possible with multiinput :)

**Comment by anabelle** [comment]
Sorry to ask so much, is this possible with all field types?

**Comment by kucrut** [comment]
Currently there are a few field types that are 'blacklisted'. I'm 
improving the JS to make this support all field types.
