### ISSUE TITLE
Multiple posts & pages

### ISSUE THREAD

**Issue by eskimirza** [kucrut/kc-settings#5]
Is it possible to have a predefined options that combines Posts/Custom Posts/Pages?

**Comment by kucrut** [comment]
Could you give more detail about this?

**Comment by eskimirza** [comment]
Let's say i create a Post Metadata (custom fields) and I want to have 2 custom fields:
1. A simple text input
2. A link for the Text Input that links to either a Post+Custom Posts+Page links which will be a Select Dropdown list

Right now i could only select either a Post or Custom Post or Page, but couldn't have it all in one Select dropdown list.

Any way to get this feature or is there any other way to do this?

**Comment by kucrut** [comment]
No, there's no built-in option for this, but you can always use a custom function for the options, e.g:

``` php
array(
    'id'      => 'sample_checkbox2',
    'title'   => 'Categories',
    'type'    => 'select',
    'options' => array('kcSettings_options_cb', 'post'),
    'args'    => array(
        'post_type' => array('page', 'post')
    )
)
```

See how to handle the current value in `kcSettings_options_cb` class located in `options.php`.

**Comment by kucrut** [comment]
See updated sample.

**Comment by eskimirza** [comment]
ok, am trying it now

edit: not sure where i should dump the code though.
