### ISSUE TITLE
add a jquery date picker to date type field

### ISSUE THREAD

**Issue by javalover28** [kucrut/kc-settings#6]
you provide date field and in which if we enter date then it save in database table in this format "dd-mm-year" ..

but in jquery user can save date in number format into the database like "yearmmdd"..hence it is a number and we can order our all post with this number...
get_posts  query in the wordpress provide a argument "orderby" so a user can get all post in the order by this date_field meta key...and this is the biggest advantage of jquery date_picker...
check these links  http://www.advancedcustomfields.com/docs/field-types/date-picker/
http://codex.wordpress.org/Template_Tags/get_posts

**Comment by kucrut** [comment]
Hello, Sorry for the late reply.

Actually, the date field will save the value in yyyy-mm-dd format, because it's the default format in most browsers that have support for the date input type. You can order your query based on the date value easily, for example:

``` php
$q = new WP_Query( array(
    'meta_query' => array(
        array(
            'key' => '_date',
            'type' => 'DATE',
        ),
    ),
    'meta_key' => '_date',
    'orderby'  => 'meta_value',
    'order'    => 'ASC',
) );

if ( $q->have_posts() ) {
    echo '<pre><code>';
    while( $q->have_posts() ) {
        $q->the_post();
        echo get_the_title()  .': '. get_post_meta( get_the_ID(), '_date', true ) .' <br />';
    }
    echo '</code></pre>';
}
wp_reset_postdata();
```
